apiVersion: network.openstack.org/v1beta1
kind: DNSMasq
metadata:
  name: dnsmasq
spec:
  replicas: 1
  options:
  - key: server
    values:
    - 192.168.122.1
  - key: local
    values:
    - '/example.com/'
  debug:
    service: false
